repos:
  - repo: https://github.com/psf/black.git
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/PyCQA/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8

